import { Toaster } from "@briefly/ui/components/sonner";
import { TooltipProvider } from "@briefly/ui/components/tooltip";
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ViewTransition } from "react";

import "@briefly/ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">
        <NuqsAdapter>
          <TooltipProvider>
            <ViewTransition>{children}</ViewTransition>
            <Toaster />
          </TooltipProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
